### PR TITLE
updated log format, added userID and sessionID to logs

### PR DESCRIPTION
**Pull request by royh1122**

### CODE REVIEW

**Comment by marcosantiagomuro** [comment]
so very nice, everything works good and even the multiple sessions are indicated in the logging

as mentioned in Facebook messenger the log for start restart and stop has to indicate the printer number that has performed the action

**Comment by marcosantiagomuro** [comment]
second thing   do we still have the 3 different types of logging? 

INFO, ERROR, and DEBUG?

**Comment by royh1122** [comment]
I didn't include the different types of logging, do you think we need them?

**Comment by marcosantiagomuro** [comment]
> I didn't include the different types of logging, do you think we need them?

nono just asking  like this is perfect  when you can add the last commit for the stop restart start button and then we merge :)

**Comment by royh1122** [comment]
ok, i have updated stop restart start log content, good to merge now

**Comment by marcosantiagomuro** [comment]
merged great!

**Review by marcosantiagomuro — COMMENTED** [review]
great

**Pull request merged**
